### ISSUE TITLE
Pylint output seems a bit suspecious

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#15] opened 2020-06-25 08:43 UTC
According to the readme file, I tried to run pylint command on the repo and while it run fine it is giving some erronous output too. Screenshot attached for the start of output.
Steps to reproduce
```
git clone https://github.com/UCL/scikit-surgeryfred
cd scikit-surgeryfred
pip install pylint
pylint --rcfile=tests/pylintrc sksurgeryfred

```
<img width="1270" alt="Screenshot 2020-06-25 at 09 36 33" src="https://user-images.githubusercontent.com/2621305/85686848-3b21b280-b6c8-11ea-8ae1-20f0b3e9de36.png">

**Comment by thompson318** [comment] 2020-06-25 09:22
Duplicate of #13

**Closed as completed by thompson318** 2020-06-25 09:22 UTC
