### ISSUE TITLE
Error when trying to execute

### ISSUE THREAD

**Issue by mianasbat** [SciKit-Surgery/scikit-surgeryfredmatplotlib#16] opened 2020-06-25 08:47 UTC
I tried to run the application but I got an error. Following are the details of the error.
Steps to reproduce on Mac
```
git clone https://github.com/UCL/scikit-surgeryfred
cd scikit-surgeryfred
python sksurgeryfred.py
```
the screenshot is
<img width="1279" alt="Screenshot 2020-06-25 at 09 43 30" src="https://user-images.githubusercontent.com/2621305/85687444-cac76100-b6c8-11ea-8e47-d778e0b9bc48.png">

**Comment by thompson318** [comment] 2020-06-25 09:19
Duplicate of #13

**Closed as completed by thompson318** 2020-06-25 09:19 UTC
